FROM php:7.4-fpm-alpine

RUN apk -U --no-cache add \
    php7-bcmath \
    php7-ctype \
    php7-curl \
    php7-dom \
    # php7-hash \
    php7-iconv \
    php7-intl \
    php7-mbstring \
    php7-openssl \
    php7-pdo_mysql \
    php7-simplexml \
    php7-soap \
    php7-xsl \
    php7-zip \
    php7-sockets \
    php7-gd \
    php7-opcache
